using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Molten.Graphics.Vulkan
{
    /// <summary>
    /// A built-in decoration type. Similar to system variables (SV_*) in HLSL.
    /// </summary>
    public enum SpirvBuiltInDecorationType
    {
        Position = 0,
        PointSize = 1,
        ClipDistance = 3,
        CullDistance = 4,
        VertexId = 5,
        InstanceId = 6,
        PrimitiveId = 7,
        InvocationId = 8,
        Layer = 9,
        ViewportIndex = 10,
        TessLevelOuter = 11,
        TessLevelInner = 12,
        TessCoord = 13,
        PatchVertices = 14,
        FragCoord = 15,
        PointCoord = 16,
        FrontFacing = 17,
        SampleId = 18,
        SamplePosition = 19,
        SampleMask = 20,
        FragDepth = 22,
        HelperInvocation = 23,
        NumWorkgroups = 24,
        WorkgroupSize = 25,
        WorkgroupId = 26,
        LocalInvocationId = 27,
        GlobalInvocationId = 28,
        LocalInvocationIndex = 29,
        WorkDim = 30,
        GlobalSize = 31,
        EnqueuedWorkgroupSize = 32,
        GlobalOffset = 33,
        GlobalLinearId = 34,
        SubgroupSize = 36,
        SubgroupMaxSize = 37,
        NumSubgroups = 38,
        NumEnqueuedSubgroups = 39,
        SubgroupId = 40,
        SubgroupLocalInvocationId = 41,
        VertexIndex = 42,
        InstanceIndex = 43,
        SubgroupEqMaskKHR = 4416,
        SubgroupGeMaskKHR = 4417,
        SubgroupGtMaskKHR = 4418,
        SubgroupLeMaskKHR = 4419,
        SubgroupLtMaskKHR = 4420,
        BaseVertex = 4424,
        BaseInstance = 4425,
        DrawIndex = 4426,
        DeviceIndex = 4438,
        ViewIndex = 4440,
        BaryCoordNoPerspAMD = 4992,
        BaryCoordNoPerspCentroidAMD = 4993,
        BaryCoordNoPerspSampleAMD = 4994,
        BaryCoordSmoothAMD = 4995,
        BaryCoordSmoothCentroidAMD = 4996,
        BaryCoordSmoothSampleAMD = 4997,
        BaryCoordPullModelAMD = 4998,
        FragStencilRefEXT = 5014,
        ViewportMaskNV = 5253,
        SecondaryPositionNV = 5257,
        SecondaryViewportMaskNV = 5258,
        PositionPerViewNV = 5261,
        ViewportMaskPerViewNV = 5262,
        FullyCoveredEXT = 5264,
        TaskCountNV = 5274,
        PrimitiveCountNV = 5275,
        PrimitiveIndicesNV = 5276,
        ClipDistancePerViewNV = 5277,
        CullDistancePerViewNV = 5278,
        LayerPerViewNV = 5279,
        MeshViewCountNV = 5280,
        MeshViewIndicesNV = 5281,
        BaryCoordKHR = 5286,
        BaryCoordNV = 5286,
        BaryCoordNoPerspKHR = 5287,
        BaryCoordNoPerspNV = 5287,
        FragSizeEXT = 5292,
        FragmentSizeNV = 5292,
        FragInvocationCountEXT = 5293,
        InvocationsPerPixelNV = 5293,
        LaunchIdNV = 5319,
        LaunchIdKHR = 5319,
        LaunchSizeNV = 5320,
        LaunchSizeKHR = 5320,
        WorldRayOriginNV = 5321,
        WorldRayOriginKHR = 5321,
        WorldRayDirectionNV = 5322,
        WorldRayDirectionKHR = 5322,
        ObjectRayOriginNV = 5323,
        ObjectRayOriginKHR = 5323,
        ObjectRayDirectionNV = 5324,
        ObjectRayDirectionKHR = 5324,
        RayTminNV = 5325,
        RayTminKHR = 5325,
        RayTmaxNV = 5326,
        RayTmaxKHR = 5326,
        InstanceCustomIndexKHR = 5328,
        InstanceCustomIndexNV = 5328,
        ObjectToWorldNV = 5330,
        ObjectToWorldKHR = 5330,
        WorldToObjectNV = 5331,
        WorldToObjectKHR = 5331,
        HitTNV = 5332,
        HitTKHR = 5332,
        HitKindNV = 5333,
        HitKindKHR = 5333,
        CurrentRayTimeNV = 5334,
        IncomingRayFlagsNV = 5351,
        IncomingRayFlagsKHR = 5351,
        RayGeometryIndexKHR = 5352,
        WarpsPerSMNV = 5374,
        SMCountNV = 5375,
        WarpIDNV = 5376,
        SMIDNV = 5377,
        CullMaskKHR = 6021
    }
}
