using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Molten.Graphics.Vulkan
{
    public enum SpirvDecorationType : uint
    {
        RelaxedPrecision = 0,
        SpecId = 1,
        Block = 2,
        BufferBlock = 3,
        RowMajor = 4,
        ColMajor = 5,
        ArrayStride = 6,
        MatrixStride = 7,
        GLSLShared = 8,
        GLSLPacked = 9,
        CPacked = 10,
        BuiltIn = 11,
        NoPerspective = 13,
        Flat = 14,
        Patch = 15,
        Centroid = 16,
        Sample = 17,
        Invariant = 18,
        Restrict = 19,
        Aliased = 20,
        Volatile = 21,
        Constant = 22,
        Coherent = 23,
        NonWritable = 24,
        NonReadable = 25,
        Uniform = 26,
        SaturatedConversion = 28,
        Stream = 29,
        Location = 30,
        Component = 31,
        Index = 32,
        Binding = 33,
        DescriptorSet = 34,
        Offset = 35,
        XfbBuffer = 36,
        XfbStride = 37,
        FuncParamAttr = 38,
        FPRoundingMode = 39,
        FPFastMathMode = 40,
        LinkageAttributes = 41,
        NoContraction = 42,
        InputAttachmentIndex = 43,
        Alignment = 44,
        MaxByteOffset = 45,
        AlignmentId = 46,
        MaxByteOffsetId = 47,
        NoSignedWrap = 4469,
        NoUnsignedWrap = 4470,
        ExplicitInterpAMD = 4999,
        OverrideCoverageNV = 5248,
        PassthroughNV = 5250,
        ViewportRelativeNV = 5252,
        SecondaryViewportRelativeNV = 5256,
        PerPrimitiveNV = 5271,
        PerViewNV = 5272,
        PerTaskNV = 5273,
        perVertexKHR = 5285,
        PerVertexNV = 5285,
        NonUniform = 5300,
        NonUniformEXT = 5300,
        RestrictPointer = 5355,
        RestrictPointerEXT = 5355,
        AliasedPointer = 5356,
        AliasedPointerEXT = 5356,
        BindlessSamplerNV = 5398,
        BindlessImageNV = 5399,
        BoundSamplerNV = 5400,
        BoundImageNV = 5401,
        SIMTCallINTEL = 5599,
        ReferencedIndirectlyINTEL = 5602,
        ClobberINTEL = 5607,
        SideEffectsINTEL = 5608,
        VectorComputeVariableINTEL = 5624,
        FuncParamIOKindINTEL = 5625,
        VectorComputeFunctionINTEL = 5626,
        StackCallINTEL = 5627,
        GlobalVariableOffsetINTEL = 5628,
        CounterBuffer = 5634,
        HlslCounterBufferGOOGLE = 5634,
        UserSemantic = 5635,
        HlslSemanticGOOGLE = 5635,
        UserTypeGOOGLE = 5636,
        FunctionRoundingModeINTEL = 5822,
        FunctionDenormModeINTEL = 5823,
        RegisterJNTEL = 5825,
        MemoryINTEL = 5826,
        NumbanksINTEL = 5827,
        BankwidthINTEL = 5828,
        MaxPrivateCopiesINTEL = 5829,
        SinglepumpINTEL = 5830,
        DoublepumpINTEL = 5831,
        MaxReplicatesINTEL = 5832,
        SimpleDualPortINTEL = 5833,
        MergeINTEL = 5834,
        BankBitsINTEL = 5835,
        ForcePow2DepthINTEL = 5836,
        BurstCoalesceINTEL = 5899,
        CacheSizeINTEL = 5900,
        DontStaticallyCoalesceINTEL = 5901,
        PrefetchINTEL = 5902,
        StallEnableINTEl = 5905,
    }
}
