using SharpDX.Direct3D;
using Molten.Graphics.Shaders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Molten.Graphics
{
    public class Material : HlslShader, IMaterial
    {
        internal MaterialPass[] Passes = new MaterialPass[0];
        internal byte[] InputStructureByteCode;

        internal string DefaultVSEntryPoint;
        internal string DefaultGSEntryPoint;
        internal string DefaultDSEntryPoint;
        internal string DefaultHSEntryPoint;
        internal string DefaultPSEntryPoint;

        Dictionary<string, MaterialPass> _passesByName;

        public int PassCount => Passes.Length;

        internal Material(GraphicsDevice device, string filename) : base(device, filename)
        {
            _passesByName = new Dictionary<string, MaterialPass>();
        }

        /// <summary>
        /// Creates a new pass using the default shader stage entry points.
        /// </summary>
        internal void AddDefaultPass()
        {
            MaterialPass defaultPass = new MaterialPass(this)
            {
                Name = "<Auto-generated pass>",
            };
            defaultPass.VertexShader.EntryPoint = DefaultVSEntryPoint;
            defaultPass.GeometryShader.EntryPoint = DefaultGSEntryPoint;
            defaultPass.DomainShader.EntryPoint = DefaultDSEntryPoint;
            defaultPass.HullShader.EntryPoint = DefaultHSEntryPoint;
            defaultPass.PixelShader.EntryPoint = DefaultPSEntryPoint;
            AddPass(defaultPass);
        }

        internal void AddPass(MaterialPass pass)
        {
            int id = 0;
            if (Passes == null)
            {
                Passes = new MaterialPass[1];
            }
            else
            {
                id = Passes.Length;
                Array.Resize(ref Passes, Passes.Length + 1);
            }

            Passes[id] = pass;
        }

        public IMaterialPass GetPass(int index)
        {
            return Passes[index];
        }

        public IMaterialPass GetPass(string name)
        {
            return _passesByName[name];
        }

        internal bool HasFlags(MaterialCommonFlags flags)
        {
            return (Flags & flags) == flags;
        }

        internal MaterialCommonFlags Flags { get; set; }

        internal IShaderValue World { get; set; }

        internal IShaderValue Wvp { get; set; }

        internal IShaderValue View { get; set; }

        internal IShaderValue Projection { get; set; }

        internal IShaderValue ViewProjection { get; set; }

        internal IShaderValue InvViewProjection { get; set; }

        internal IShaderValue DiffuseTexture { get; set; }

        internal IShaderValue NormalTexture { get; set; }

        internal IShaderValue EmissiveTexture { get; set; }

        internal IShaderValue EmissivePower { get; set; }
    }

    /// <summary>
    /// Represents various optional/mandatory properties a material might have, which the renderer can automatically use.
    /// </summary>
    [Flags]
    internal enum MaterialCommonFlags
    {
        None = 0,

        Common = 1,

        Object = 1 << 1,

        GBuffer = 1 << 2,

        GBufferTextures = 1 << 3,
    }
}
